### ISSUE TITLE
마이페이지 div 간격 조정

### ISSUE THREAD

**Issue by HaeunOh** [TEAM-POKY/TripTrav#203]
<img width="1324" alt="스크린샷 2024-10-11 오후 6 48 53" src="https://github.com/user-attachments/assets/29bb3f18-d311-4b85-af4c-1a2ab5eea06c">

헤더랑 마이페이지랑 너무 딱 붙으니까 적절히 수정해야될거같아용 @wanted2001

**Comment by wanted2001** [comment]
margin-top 으로 50px 더 주도록 수정 했습니다.

**Comment by wanted2001** [comment]
margin-top 50px 더 주도록 하여 수정하였습니다.
